My OSX 10.10 was missing pySerial
While trying the demo on Mac OSX 10.10, I noticed my installation was missing the serial library.
I am not sure if I run the Vanilla OSX Python or the brew version of Python, but I needed to do this for things to work, else:
```
python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from mote import Mote
  File "/usr/local/lib/python2.7/site-packages/mote/__init__.py", line 1, in <module>
    import serial
ImportError: No module named serial
```